services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Ivoz\Provider\Infrastructure\Api\Client\Client:
    arguments:
      $httpClient: '@ivoz.api_platform.http.client'
      $jwtTokenManager: '@lexik_jwt_authentication.jwt_manager'

  Ivoz\Core\Domain\Service\ApiClientInterface:
    '@Ivoz\Provider\Infrastructure\Api\Client\Client'

  Ivoz\Provider\Infrastructure\Hostname\GetHostname: ~
  Ivoz\Provider\Domain\Service\HostnameGetter:
    '@Ivoz\Provider\Infrastructure\Hostname\GetHostname'

  ################################################
  ## Listeners
  ################################################
  Ivoz\Provider\Infrastructure\Api\Timezone\UserTimezoneInjector:
    arguments:
      $tokenStorage: '@security.token_storage'
    tags:
      - { name: kernel.event_listener, event: kernel.request, priority: 5 }

  Ivoz\Provider\Infrastructure\Api\Jwt\JWTCreatedListener:
    tags:
      - { name: kernel.event_listener, event: lexik_jwt_authentication.on_jwt_created, method: onJWTCreated }

when@test:
  services:
    _defaults:
      autowire: true
      autoconfigure: true
      public: false

    Ivoz\Provider\Infrastructure\Api\Client\FakeClient: ~
    Ivoz\Core\Domain\Service\ApiClientInterface:
      '@Ivoz\Provider\Infrastructure\Api\Client\FakeClient'