#include conf.d/mapperList.yaml
#include conf.d/actions.yaml
#include conf.d/documentationLink.yaml

production:
  main:
    module: klearMatrix
    defaultScreen: conferenceRoomsList_screen
  screens: &conferenceRooms_screensLink
    conferenceRoomsList_screen: &conferenceRoomsList_screenLink
      controller: list
      pagination:
        items: 25
      <<: *ConferenceRooms
      class: ui-silk-text-list-bullets
      title: _("List of %s %2s", ngettext('Conference room', 'Conference rooms', 0), "[format| (%parent%)]")
      info:
        <<: *documentationLink
        href: "/doc/en/administration_portal/client/vpbx/routing_endpoints/conference_rooms.html"
      forcedValues:
        <<: *forcedCompany
      fields: &conferenceRooms_fieldsLink
        order:
          name: true
          maxMembers: true
          pinProtected: true
          pinCode: true
        blacklist:
          announceUserCount: true
        options:
          title: _("Options")
          screens:
            conferenceRoomsEdit_screen: $[${auth.acls.ConferenceRooms.update} && ${auth.companyVPBX}]
          dialogs:
            conferenceRoomsDel_dialog: $[${auth.acls.ConferenceRooms.delete} && ${auth.companyVPBX}]
          default: conferenceRoomsEdit_screen
      options:
        title: _("Options")
        screens:
          conferenceRoomsNew_screen: $[${auth.acls.ConferenceRooms.create} && ${auth.companyVPBX}]
        dialogs:
          conferenceRoomsDel_dialog: $[${auth.acls.ConferenceRooms.delete} && ${auth.companyVPBX}]
    conferenceRoomsNew_screen: &conferenceRoomsNew_screenLink
      <<: *ConferenceRooms
      controller: new
      class: ui-silk-add
      label: true
      multiInstance: true
      title: _("Add %s", ngettext('Conference room', 'Conference rooms', 1), "[format| (%parent%)]")
      forcedValues:
        <<: *forcedCompany
      fixedPositions: &ConferenceRoomsFixedPositions_link
        group0:
          label: _("Basic Configuration")
          colsPerRow: 3
          fields:
            name: 2
            maxMembers: 1
            announceUserCount: 2
        group1:
          label: _("Authentication Settings")
          colsPerRow: 3
          fields:
             pinProtected: 1
             pinCode: 1
      shortcutOption: N
    conferenceRoomsEdit_screen: &conferenceRoomsEdit_screenLink
      <<: *ConferenceRooms
      controller: edit
      class: ui-silk-pencil
      label: false
      labelOnPostAction: _("Edit %s %2s", ngettext('Conference room', 'Conference rooms', 1), "[format| (%item%)]")
      title: _("Edit %s %2s", ngettext('Conference room', 'Conference rooms', 1), "[format| (%item%)]")
      forcedValues:
        <<: *forcedCompany
      fixedPositions:
        <<: *ConferenceRoomsFixedPositions_link
  dialogs: &conferenceRooms_dialogsLink
    conferenceRoomsDel_dialog: &conferenceRoomsDel_dialogLink
      <<: *ConferenceRooms
      controller: delete
      class: ui-silk-bin
      labelOption: false
      title: _("Delete %s", ngettext('Conference room', 'Conference rooms', 1))
      description: _("Do you want to delete this %s?", ngettext('Conference room', 'Conference rooms', 1))
      message: _("%s successfully deleted.", ngettext('Conference room', 'Conference rooms', 1))
      multiItem: 1
      labelOnList: 1
staging:
  _extends: production
testing:
  _extends: production
development:
  _extends: production
localdev:
  _extends: production
