########################################
## Custom models
########################################
Model\Dashboard\Dashboard:
  itemOperations:
    get_my_dasboard:
      access_control: '"ROLE_COMPANY_USER" in roles'
      method: 'GET'
      path: '/my/dashboard'
      route_name: 'get_my_dasboard'
      parameters: []
      swagger_context:
        produces:
          - 'application/json'
        tags:
          - My
  collectionOperations: []

Model\Token:
  itemOperations: []
  collectionOperations:
    post_auth_token_exchange:
      method: 'POST'
      path: '/token/exchange'
      route_name: 'post_auth_token_exchange'
      swagger_context:
        consumes:
        - 'application/x-www-form-urlencoded'
        produces:
        - 'application/json'
        tags:
        - Auth
        parameters:
        - name: token
          in: formData
          type: string
          required: true
          description: 'Client admin token'
        - name: username
          in: formData
          type: string
          required: false
          description: 'Target user admin email'

Model\LastMonthCalls:
  itemOperations:
    get_my_last_month_calls:
      access_control: '"ROLE_COMPANY_USER" in roles'
      method: 'GET'
      path: '/my/last_month_calls'
      route_name: 'get_my_last_month_calls'
      swagger_context:
        produces:
        - 'application/json'
        tags:
        - My
  collectionOperations: []

Model\UserStatus:
  attributes:
    access_control: '"ROLE_COMPANY_USER" in roles'
  itemOperations:
    get:
      method: 'GET'
      path: '/my/status'
      route_name: 'get_my_status'
      swagger_context:
        tags:
          - My
        parameters: []
  collectionOperations: {}

Model\CallStats:
  attributes:
    access_control: '"ROLE_COMPANY_USER" in roles'
  itemOperations:
    get:
      method: 'GET'
      path: '/my/call_stats'
      route_name: 'get_my_call_stats'
      swagger_context:
        tags:
          - My
        parameters: []
  collectionOperations: {}